### ISSUE TITLE
Expected result

### ISSUE THREAD

**Issue by Nordal** [HewlettPackard/oneview-powershell-samples#1]
Hi,
Thanks for providing an easy way to locate affected drives.
I have one question though. What is the expected result? I got a csv file only with head lines, I assume that´s because I dont have any affected drives, but it could also be an error collecting drive info?

**Comment by Nordal** [comment]
Looking at the script, it really looks like an error not getting any data.
Im running the OV version against HP OpenView Appliance Version 4.20.01.385523.01 with Gen9 servers

**Comment by DungKHoang** [comment]
Please download the latest version ( posted 1 hour ago).
I have tested on OV 4.20 and OV 5.0 with Gen8/Gen9/Gen10 servers and also D3940. If the server has no SAS -SSD drive the CSV file is empty
By default, I look only for SAS-SSD drives
If you want other types of drives, add the parameters InterfaceType and mediaType
The README file provides an example

**Comment by Nordal** [comment]
Hi Dung,
Ran the new version, AND remembered to change the interfacetype to SATA.
Everything worked as expected. Thanks for sharing.
