### ISSUE TITLE
OneView Inventory SAS SSD - (503) Server Unavailable

### ISSUE THREAD

**Issue by Ax2L** [HewlettPackard/oneview-powershell-samples#2]
Hello all,

I have an issue with the OV-Get-Disks.ps1 Script.
First of all, I installed all the needed Modules that are mention in the Readme.
I also added: https://www.powershellgallery.com/packages?q=HPERedfish

But I still face the issue:

![image](https://user-images.githubusercontent.com/42996373/69962113-99f5c380-150d-11ea-9520-81ff16fc7551.png)

Can you please help me out?

I tried it with both examples (for SAS and SATA).

Thank you and Best Regards

**Comment by DungKHoang** [comment]
Hi
Try  : 
connect-hpovMgmt -hostname <your-OV-address> -username <OV admin name > -password <OV-password>
$s = get-hpovserver -name "bma0624, bay 1"
$ilosession = $s | get-HPOViloSso -iloRestSession

Does it return an error?
If yes please check this server in the GUI

**Comment by Ax2L** [comment]
Hey Dung,

thank you so much for your quick response!
Unfortunately, i also face here the same:

![image](https://user-images.githubusercontent.com/42996373/69963156-e3471280-150f-11ea-8ecb-0c2ca3122eaf.png)

i tried it on 3 Consoles... i face this error on each console...
Strange is, that i become the error just one time when i try the command again, it tells me: 

> WARNING: You are already connected to console123.example 

Do i miss something?

Thank you!

**Comment by DungKHoang** [comment]
Two things
a) Try to troubleshooting the error with the OV GUI. What is the state of those servers?. Can you open an iLO console from those servers? 
b) As for the warning , there must be something difficult to troubleshoot with email
Try to reset the ILO console on these servers
If it does not fix, please log a call to HPE support 
Regards
/Dung

**Comment by Ax2L** [comment]
Hello Dung,

a) i checked the Server, and see that we have there an issue with the UUID.

But when i now try it on the other Console, I see that the Script tries to collect data from the same Enclosure (Hostname).
Which is definitely only on the first Console.

So i disconnected from all Consoles and did it again. But it still tries to collect data from a server that is not on the Console.

I will try now to collect the data over the ILO.
And to reset it afterward.

Thank you for your help!

Best Regards
Sewa

**Comment by DungKHoang** [comment]
I will take a look at how to handle error message from Redfish.
In the meanwhile, you can set the environment variable ErrorActionPreference to bypass errors like:
 $ErrorActionPreference = 'SilentlyContinue'
or
$ErrorActionPreference = 'Continue'
before running the script
It's not very clean but it should avoid terminating the script
/Dung

**Comment by DungKHoang** [comment]
I just add code to handle error with iLO
Please download the latest version

**Comment by Ax2L** [comment]
Hello Dung,

thank you for the Updates.
I did it now as follow:

i understand the Script just grep the Server list from the OV Appliance.
And afterward, it will check the Server over the ILO.

So i have now a possible connection to the ILO.
But I run now in an "SSL connection" issue.

Please check:
![image](https://user-images.githubusercontent.com/42996373/70142747-39e05800-169a-11ea-9303-f89413a0195f.png)

I saw in the Script that you disable the authentication.
Is this option may be coming from the ILO Board?

I have no Match in my CSV reg the SSD.
We used here an OV Console where one Server has this SSD Issue.

Thank you and Best Regards
Sewa

**Comment by Anxhub** [comment]
someone has the full script?

**Comment by DungKHoang** [comment]
The script is re-posted. Close issue
If you still have problem, please log a new issue
