### ISSUE TITLE
filter out G7 systems from the collection

### ISSUE THREAD

**Issue by davidvf** [HewlettPackard/oneview-powershell-samples#3]
Hi, 

This issue is related to:
oneview-powershell-samples/OneView-Inventory-SAS-SSD/OV-Get-Disks.ps1

Can you skip getting the disks in servers in OneView when the model is not Gen8/9 or 10?
My customer tried the script but it is failing as certain enclosures still contain G7 systems.

**Comment by DungKHoang** [comment]
Hi David
Just update the script with a check on ILO3 that would skip G7 servers
Please download the latest version
