### ISSUE TITLE
SAS SSD Code missing

### ISSUE THREAD

**Issue by DanRobinsonHPE** [HewlettPackard/oneview-powershell-samples#5]
https://github.com/HewlettPackard/oneview-powershell-samples/tree/master/OneView-Inventory-SAS-SSD is no longer available.

**Comment by coredumpster** [comment]
Looks like it was removed.  :/

https://github.com/HewlettPackard/oneview-powershell-samples/commit/7d7137b96171ebe2cf54ec985d9526cee0672c6e

**Comment by Anxhub** [comment]
someone has the full script?

**Comment by DungKHoang** [comment]
It is back now
