### ISSUE TITLE
'Cannot Connect to server' for all DL360 Gen 10 - Gen 9's are fine  

### ISSUE THREAD

**Issue by ric9887** [HewlettPackard/oneview-powershell-samples#6]
I have a problem running OV-Get-Disks.ps1 against our OV 5.00.01-0410269.
Each Gen10 connection reports 'Cannot Connect to Server, but all connections to Gen9 DL360's  successfully retrieve the disk information.

![Cannot Connect](https://user-images.githubusercontent.com/5351780/73350253-96b85300-4284-11ea-865e-4d243c30d7b0.jpg)

Could you possiblily help with some guidence on why this should happen please.
Regards
Rich

**Comment by DungKHoang** [comment]
Hi Rich
Basically the script connects to the ilO ( either thru OV or directly to iLO) to get the inventory. There are 2 versions of the scripts : one with OV and one with iLO
So to troubleshoot the Gen10 connectivity to iLO, I suggest the following:
a) From the GUI of OV, connect to the iLO admin of each Gen10 server
b) Using iLO ip address, open a browser to log in to iLO
c) If youc an connect to ILO and have credential to login, try to use the script with iLO ( instead of OV)
This will help to find out why the script cannot connect to the Gen10 server's ilo
Let me know how it works
/Dung

**Comment by ric9887** [comment]
Hi Doug, thanks for getting back to me.
I have done what you have suggested and can connect using the administrator account to each iLo (which is different to the credntials defined in OV) - but both accounts can login directly to the iLo GUI's in a browser ok, using the IP address defined in OV for each iLo.
I get a similar 'Connot connect to iLo' message when I try running the iLo script (after updating the csv file with the IP's / acccount names / passwords)

![Cannot Connect - iLo](https://user-images.githubusercontent.com/5351780/73379219-c897dc80-42b9-11ea-84b9-1d5a10ebfcba.jpg)

**Comment by DungKHoang** [comment]
Hi Rich,

Can you try the following from a Powershell console:
 $iloName         = <ilo-ip-address>
 $username       = 'administrator'
 $securePassword = '<admin-password>'| ConvertTo-SecureString -AsPlainText -Force
 $cred           = New-Object System.Management.Automation.PSCredential  -ArgumentList $userName, $securePassword
$iloSession     = Connect-HPERedfish -Address $iloName -Cred $cred -DisableCertificateAuthentication
Get-HPERedfishDataRaw  -session $iloSession -DisableCertificateAuthentication  -odataid '/redfish/v1/Systems' 

and post the output if there is error

Thanks!

**Comment by DungKHoang** [comment]
sorry
this line
$securePassword = ''| ConvertTo-SecureString -AsPlainText -Force 
 should read
$securePassword = '<admin-password>'| ConvertTo-SecureString -AsPlainText -Force

**Comment by DungKHoang** [comment]
Hmm not sure why some text is cut off
$iloName = IP-Address
$securePassword = 'admin-password'| ConvertTo-SecureString -AsPlainText -Force

**Comment by ric9887** [comment]
Had to wrap the ip address in '' as it said the string was empty otherwise.
Not sure if that was the right thing to do, but it didnt report it as being empty once I did that.
Hope it helps.

![Cannot Connect - Test](https://user-images.githubusercontent.com/5351780/73381925-7f965700-42be-11ea-9b72-9fdb644659e6.jpg)

**Comment by DungKHoang** [comment]
Thanks for the output.
Can you try this script after renaming to ps1? I basically remove the try{} and catch{}

[iLO-Get-Disks.txt](https://github.com/HewlettPackard/oneview-powershell-samples/files/4129672/iLO-Get-Disks.txt)

**Comment by ric9887** [comment]
![Cannot Connect - Test2](https://user-images.githubusercontent.com/5351780/73384218-bb332000-42c2-11ea-9a29-f5b49b5834da.jpg)

**Comment by DungKHoang** [comment]
Thanks!
I found the error. The endpoint for ArrayControllers is not correctly built.
/redfish/v1/Systems/1/SmartStorage/ArrayControllers
instead of 
/redfish/v1/Systems/1SmartStorage/ArrayControllers
please try this one:
[iLO-Get-Disks.txt](https://github.com/HewlettPackard/oneview-powershell-samples/files/4129956/iLO-Get-Disks.txt)

**Comment by ric9887** [comment]
Hi Doug, that now works for a Gen10 server - but errors for a Gen9.
Below is the error returned for Gen9 followed by a successful Gen10

![Cannot Connect - Test3](https://user-images.githubusercontent.com/5351780/73386552-efa8db00-42c6-11ea-8d45-6d365d543a30.jpg)

**Comment by DungKHoang** [comment]
Yes, I was suspecting that
Seems like the endpoint has changed between Gen9 and Gen10 servers
Will look into this

**Comment by ric9887** [comment]
Hi Doug, your help is very much appreciated.
I dont know if this is of any help, but I found a post which extracts disk information from Gen 10 servers directly from the OV server - which apparently can not be done for Gen 9 servers.

(Get-HPOVServer | ? model -match 'Gen10' |  %{ sr -uri ($_.uri + '/localStorage' )}).Data

However, I am not skilled enough to manipulate the above's output to anything which I can use, but maybe you are able to gain something from it ?

**Comment by DungKHoang** [comment]
Yes,
I had that function in the OV-GetDisks.ps1 ( Function Gen10-Get-disk) but do not use that as I am looking for a generic function that works for both Gen9 and Gen10 as someone may not have OV in their environment
So will need to fix the ilo-get-disk function

**Comment by DungKHoang** [comment]
Or may have OV managing mix of Gen9 and Gen10

**Comment by ric9887** [comment]
I would just comment that relying on the iLo's being online to retrieve the info is a bit of a pain for us, when the disk S/N's (which is the bit we are interested in) - is 'reportable on' even when the servers are offline for Gen10's.
I am sure you realise your scripts are referenced by HPE regarding a firmware bug to cross reference against know problematic S/N SSD's.
Any further help I can offer, please let me know.

**Comment by DungKHoang** [comment]
Thanks for sharing your concern. Yes, the script was originally developed to help customers to get an inventory of their SSD disks with regard to the firmware bug as you mentioned.
As for iLO, I'd assume that it is always online. If they are offline, even OV cannot get an accurate inventory of ILO config. Also OV does report only Gen10 disks and is not able to do the same for Gen9.
Anyway , here are the 2 scripts updated. Please give them a try and let me know
[OV-Get-Disks.txt](https://github.com/HewlettPackard/oneview-powershell-samples/files/4130279/OV-Get-Disks.txt)
[iLO-Get-Disks.txt](https://github.com/HewlettPackard/oneview-powershell-samples/files/4130280/iLO-Get-Disks.txt)

**Comment by ric9887** [comment]
Hi Doug, they both work great - and the OV one appears to report on offline Gen10 iLo's as well.
Just to let you know, we are perhaps a little odd, but many of our Gen10 servers are in transit around the globe, so can not be guaranteed to be online when we run the report. I realise that OV does not store HDD/SSD information for Gen 9's, but the ability to report on Gen10's which are offline is most useful (their HDD/SSD's do not change when in transit).
Many thanks for your help, and hope it hasn't caused you a headache.
Regards
Rich

**Comment by DungKHoang** [comment]
Great to hear!
Will update the scripts then
Thanks for reporting the issue!

**Comment by DungKHoang** [comment]
Scripts updated
